version: "3"

services:
  nginx:
    image: "nginx:stable"
    volumes:
      - ".:/var/www/html:rw"
      - "./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro"
    healthcheck:
      test: [ "CMD-SHELL", "service nginx status || exit 1" ]
      timeout: 2s
      retries: 10
      interval: 5s
    restart: "unless-stopped"
    networks:
      default:
        aliases:
          - "mailer.press"
          - "mailhog.mailer.press"

  mailer:
    user: "${UID:-1000}:${GID:-1000}"
    environment:
      - XDEBUG_TRIGGER
      - XDEBUG_CONFIG
      - PHP_IDE_CONFIG=serverName=mailer.press
    build:
      context: "./docker/php"
      args:
        UID: ${UID:-1000}
        GID: ${GID:-1000}
        UNAME: ${UNAME:-docker}
    volumes:
      - ".:/var/www/html:rw"
    depends_on:
      nginx:
        condition: service_healthy
      mysql:
        condition: service_healthy
      redis:
        condition: service_healthy
      mailhog:
        condition: service_started
    restart: "unless-stopped"

  cron:
    build:
      context: "./docker/php"
      args:
        UID: ${UID:-1000}
        GID: ${GID:-1000}
        UNAME: ${UNAME:-docker}
    volumes:
      - ".:/var/www/html:rw"
    depends_on:
      mailer:
        condition: service_started
      mysql:
        condition: service_healthy
    entrypoint: ["/usr/local/bin/cron.sh"]
    restart: "unless-stopped"

  hermes-worker:
    user: "${UID:-1000}:${GID:-1000}"
    build:
      context: "./docker/php"
      args:
        UID: ${UID:-1000}
        GID: ${GID:-1000}
        UNAME: ${UNAME:-docker}
    volumes:
      - ".:/var/www/html:rw"    
    depends_on:
      mailer:
        condition: service_started
      mysql:
        condition: service_healthy
    entrypoint: ["php", "bin/command.php", "worker:hermes"]
    restart: "unless-stopped"

  mail-worker:
    user: "${UID:-1000}:${GID:-1000}"
    build:
      context: "./docker/php"
      args:
        UID: ${UID:-1000}
        GID: ${GID:-1000}
        UNAME: ${UNAME:-docker}
    volumes:
      - ".:/var/www/html:rw"
    depends_on:
      mailer:
        condition: service_started
      mailhog:
        condition: service_started
    entrypoint: ["php", "bin/command.php", "worker:mail"]
    restart: "unless-stopped"

  mysql:
    image: "mysql:8.0"
    cap_add:
      - SYS_NICE  
    volumes:
      - "mysql-data:/var/lib/mysql"
      - ".:/data"
    command:
      - "--character-set-server=utf8mb4"
      - "--collation-server=utf8mb4_unicode_ci"
      - "--skip-character-set-client-handshake"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "no"
      MYSQL_ROOT_PASSWORD: "secret"
      MYSQL_DATABASE: "mailer"
    healthcheck:
      test: [ "CMD", "mysqladmin" , "ping", "-h", "localhost" ]
      timeout: 2s
      retries: 10
      interval: 5s
    restart: "unless-stopped"

  redis:
    image: "redis:6.2"
    volumes:
      - "redis-data:/data"
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]
      timeout: 2s
      retries: 10
      interval: 5s
    restart: "unless-stopped"

  mailhog:
    image: "mailhog/mailhog:v1.0.1"
    environment:
      MH_HOSTNAME: "mailhog.mailer.press"

volumes:
  mysql-data:
    driver: local
  redis-data:
    driver: local

networks:
  default:
