version: "3"

services:
  nginx:
    image: "nginx:stable"
    volumes:
      - ".:/var/www/html:rw"
      - "./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro"
    restart: "unless-stopped"
    networks:
      default:
        aliases:
          - "mailer.press"
          - "mailhog.mailer.press"

  mailer:
    build: "docker/php"
    volumes:
      - ".:/var/www/html:rw"
    depends_on:
      - "nginx"
      - "mysql"
      - "redis"
      - "mailhog"
    restart: "unless-stopped"

  cron:
    build: "docker/php"
    volumes:
      - ".:/var/www/html:rw"
    depends_on:
      - "mailer"
      - "mysql"
    entrypoint: ["/root/cron.sh"]
    restart: "unless-stopped"

  hermes-worker:
    build: "docker/php"
    volumes:
      - ".:/var/www/html:rw"    
    depends_on:
      - "mailer"
      - "mysql"
    entrypoint: ["php", "bin/command.php", "worker:hermes"]
    restart: "unless-stopped"

  mail-worker:
    build: "docker/php"
    volumes:
      - ".:/var/www/html:rw"
    depends_on:
      - "mailer"
    entrypoint: ["php", "bin/command.php", "worker:mail"]
    restart: "unless-stopped"

  mysql:
    image: "mysql:8.0"
    cap_add:
      - SYS_NICE  
    volumes:
      - "mysql-data:/var/lib/mysql"
      - ".:/data"
    command:
      - "--character-set-server=utf8mb4"
      - "--collation-server=utf8mb4_unicode_ci"
      - "--skip-character-set-client-handshake"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "no"
      MYSQL_ROOT_PASSWORD: "secret"
      MYSQL_DATABASE: "mailer"
    restart: "unless-stopped"

  redis:
    image: "redis:3.2"
    volumes:
      - "redis-data:/data"
    restart: "unless-stopped"

  mailhog:
    image: "mailhog/mailhog:v1.0.1"
    environment:
      MH_HOSTNAME: "mailhog.mailer.press"

volumes:
  mysql-data:
    driver: local
  redis-data:
    driver: local

networks:
  default:
